# Generated by Django 6.0.1 on 2026-02-12 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_create_initial_tables'),
    ]

    operations = [
        # Create Collateral table
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={'db_table': 'collateral', 'managed': True},
        ),
        # Create Conditions table
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={'db_table': 'conditions', 'managed': True},
        ),
        # Create Document table
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={'db_table': 'document', 'managed': True},
        ),
        # Create Services table
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={'db_table': 'services', 'managed': True},
        ),
    ]
