# Generated manually — remove duplicate Django built-in models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_exchangerateconfig_floatmenusocials_and_more'),
    ]

    operations = [
        # Remove models that duplicate Django's built-in auth/admin/contenttypes/sessions
        # These were auto-generated by inspectdb but clash with django.contrib.* apps
        migrations.DeleteModel(name='AuthGroupPermissions'),
        migrations.DeleteModel(name='AuthUserGroups'),
        migrations.DeleteModel(name='AuthUserUserPermissions'),
        migrations.DeleteModel(name='DjangoAdminLog'),
        migrations.DeleteModel(name='AuthGroup'),
        migrations.DeleteModel(name='AuthPermission'),
        migrations.DeleteModel(name='AuthUser'),
        migrations.DeleteModel(name='DjangoContentType'),
        migrations.DeleteModel(name='DjangoMigrations'),
        migrations.DeleteModel(name='DjangoSession'),
    ]
